// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/home/app-icon.vue')['default']
    AppShell: typeof import('./src/components/app-shell.vue')['default']
    IconButton: typeof import('./src/components/icon-button.vue')['default']
    MArrowBackIosNew: typeof import('~icons/material-symbols/arrow-back-ios-new')['default']
    MBackspace: typeof import('~icons/material-symbols/backspace')['default']
    MBackspaceOutline: typeof import('~icons/material-symbols/backspace-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
