// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/_shared/app-container.vue')['default']
    AppContent: typeof import('./src/components/_shared/app-content.vue')['default']
    AppIcon: typeof import('./src/components/app-icon.vue')['default']
    AppTabItem: typeof import('./src/components/_shared/app-tab-item.vue')['default']
    BInput: typeof import('./src/components/_shared/b-input.vue')['default']
    MAdd: typeof import('~icons/material-symbols/add')['default']
    MBackspaceOutline: typeof import('~icons/material-symbols/backspace-outline')['default']
    MChevronLeft: typeof import('~icons/material-symbols/chevron-left')['default']
    MFiberManualRecordOutline: typeof import('~icons/material-symbols/fiber-manual-record-outline')['default']
    MGridViewRounded: typeof import('~icons/material-symbols/grid-view-rounded')['default']
    MHomeOutlineRounded: typeof import('~icons/material-symbols/home-outline-rounded')['default']
    MInfoOutline: typeof import('~icons/material-symbols/info-outline')['default']
    MLocationOnOutline: typeof import('~icons/material-symbols/location-on-outline')['default']
    MMailOutline: typeof import('~icons/material-symbols/mail-outline')['default']
    MPersonRounded: typeof import('~icons/material-symbols/person-rounded')['default']
    MSchoolOutline: typeof import('~icons/material-symbols/school-outline')['default']
    ProjectCard: typeof import('./src/components/about/project-card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('@headlessui/vue')['Tab']
    TabGroup: typeof import('@headlessui/vue')['TabGroup']
    TabList: typeof import('@headlessui/vue')['TabList']
    TabPanels: typeof import('@headlessui/vue')['TabPanels']
  }
}
