// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/app-container.vue')['default']
    AppContent: typeof import('./src/components/app-content.vue')['default']
    AppIcon: typeof import('./src/components/home/app-icon.vue')['default']
    BIcon: typeof import('./src/components/b-icon.vue')['default']
    BInput: typeof import('./src/components/b-input.vue')['default']
    MBackspace: typeof import('~icons/material-symbols/backspace')['default']
    MChevronLeft: typeof import('~icons/material-symbols/chevron-left')['default']
    MDrawOutline: typeof import('~icons/material-symbols/draw-outline')['default']
    MFiberManualRecordOutline: typeof import('~icons/material-symbols/fiber-manual-record-outline')['default']
    MHomeOutlineRounded: typeof import('~icons/material-symbols/home-outline-rounded')['default']
    MInfoOutline: typeof import('~icons/material-symbols/info-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
